version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.20
    - 6.2.2
    - 6.2.7
  - dependency-name: "@storybook/addons"
    versions:
    - 6.1.20
    - 6.2.2
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  commit-message:
    prefix: chore
    include: scope
